# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jlv < Formula
  desc "JSON Log Viewer tool."
  homepage "https://github.com/hedhyw/homebrews"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/json-log-viewer/releases/download/v0.2.4/jlv_darwin_amd64.tar.gz"
      sha256 "88d9cd4170237a557819a463ffcd8b313249a868273d8dce1eafc34c0b2fc200"

      def install
        bin.install "jlv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hedhyw/json-log-viewer/releases/download/v0.2.4/jlv_darwin_arm64.tar.gz"
      sha256 "2d685a62261549198e914229df40d09991da21435868cc4b1c16ea6fba333133"

      def install
        bin.install "jlv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/json-log-viewer/releases/download/v0.2.4/jlv_linux_arm.tar.gz"
      sha256 "05e30dd17e914a2d0a4ceb4a654f5a110a255286beec687806af9d4eedfe3fe1"

      def install
        bin.install "jlv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/json-log-viewer/releases/download/v0.2.4/jlv_linux_amd64.tar.gz"
      sha256 "7bf38217f9d1ad53c39000619e6c24f1820ad17b87451843cbaf3aaa7e356b8a"

      def install
        bin.install "jlv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/json-log-viewer/releases/download/v0.2.4/jlv_linux_arm64.tar.gz"
      sha256 "f59e7982e181a7e17436b8145c9b625da2a10eb9ef2f4552d785c1c76d06233d"

      def install
        bin.install "jlv"
      end
    end
  end

  test do
    system "#{bin}/jlv", "-help"
  end
end
