# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jlv < Formula
  desc "JSON Log Viewer tool."
  homepage "https://github.com/hedhyw/homebrews"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/json-log-viewer/releases/download/v1.8.0/jlv_darwin_amd64.tar.gz"
      sha256 "a30450ff6c76291585036231aeb74a01740c56bd8aa8f08dc98b75c9b9ee1a53"

      define_method(:install) do
        bin.install "jlv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hedhyw/json-log-viewer/releases/download/v1.8.0/jlv_darwin_arm64.tar.gz"
      sha256 "b89d7ceff5586034063f08e22201919ba4ce7fe607bb43b10552c458edc6913f"

      define_method(:install) do
        bin.install "jlv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/json-log-viewer/releases/download/v1.8.0/jlv_linux_amd64.tar.gz"
      sha256 "997ddb67a7453c51b986d2078c0419278491abf80cfe522e0d5eb329a260fa3d"
      define_method(:install) do
        bin.install "jlv"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/json-log-viewer/releases/download/v1.8.0/jlv_linux_arm.tar.gz"
      sha256 "c1aa3e35eca2b80458f8ad6542cd349c14840ab2d0c5e25410d7d91c2e0435c9"
      define_method(:install) do
        bin.install "jlv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/json-log-viewer/releases/download/v1.8.0/jlv_linux_arm64.tar.gz"
      sha256 "b0532f9fc6986f6790fb677a12f58635eb62e05a7da26f98bfce8b517b5c507e"
      define_method(:install) do
        bin.install "jlv"
      end
    end
  end

  test do
    system "#{bin}/jlv", "-help"
  end
end
