# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Otelinji < Formula
  desc "OpenTelemetry auto-instrumentation tool for Golang."
  homepage "https://github.com/hedhyw/homebrews"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hedhyw/otelinji/releases/download/v0.0.1/otelinji_darwin_arm64.tar.gz"
      sha256 "48b8d884b5e4fcc8e1506a8f059fba0ce01022d74f37630b88ba789fab6b6089"

      def install
        bin.install "otelinji"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/otelinji/releases/download/v0.0.1/otelinji_darwin_amd64.tar.gz"
      sha256 "e59ae3f926a5b4d9710ebb0aef96729c0bec202b79f78aa9574c5eb0055706fd"

      def install
        bin.install "otelinji"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/otelinji/releases/download/v0.0.1/otelinji_linux_arm.tar.gz"
      sha256 "1bb0ffc6b74bda7b526b76f52260cb0bffffa72ed2e3851215435bd8fe90b126"

      def install
        bin.install "otelinji"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/otelinji/releases/download/v0.0.1/otelinji_linux_amd64.tar.gz"
      sha256 "ac48e6895f613eef27f81fa2216028873118b3c8b068e8a70781482b7bf79bc7"

      def install
        bin.install "otelinji"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/otelinji/releases/download/v0.0.1/otelinji_linux_arm64.tar.gz"
      sha256 "ca1cfb91ac5d357d89998528a38db96eae2e4a3ffb9e61504a5b9dac9f646f66"

      def install
        bin.install "otelinji"
      end
    end
  end

  test do
    system "#{bin}/otelinji", "-help"
  end
end
