# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Otelinji < Formula
  desc "OpenTelemetry auto-instrumentation tool for Golang."
  homepage "https://github.com/hedhyw/homebrews"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hedhyw/otelinji/releases/download/v0.2.1/otelinji_darwin_arm64.tar.gz"
      sha256 "9dd262bd7959a7b0388880fed4f583b34626def7b5ffb6559bdeaf45ee769c14"

      def install
        bin.install "otelinji"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/otelinji/releases/download/v0.2.1/otelinji_darwin_amd64.tar.gz"
      sha256 "2ac67a55cb054bd3092ee18bcc4d7aec18929174d98b9820821de39e9528d064"

      def install
        bin.install "otelinji"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/otelinji/releases/download/v0.2.1/otelinji_linux_amd64.tar.gz"
      sha256 "33e0c05682249c5be373e9f03ffdaea31f8cd7d169eca446b4afec3d25765188"

      def install
        bin.install "otelinji"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/otelinji/releases/download/v0.2.1/otelinji_linux_arm64.tar.gz"
      sha256 "162584946baf82e934c27b4b1b7a2ffb2c42520d9b6f6e8bd6865765b7b71191"

      def install
        bin.install "otelinji"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/otelinji/releases/download/v0.2.1/otelinji_linux_arm.tar.gz"
      sha256 "051ee2f13edc320e701853edb9170e4dc7c12145e4d03f08e92287e3666c4414"

      def install
        bin.install "otelinji"
      end
    end
  end

  test do
    system "#{bin}/otelinji", "-help"
  end
end
