# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Otelinji < Formula
  desc "OpenTelemetry auto-instrumentation tool for Golang."
  homepage "https://github.com/hedhyw/homebrews"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/otelinji/releases/download/v0.2.2/otelinji_darwin_amd64.tar.gz"
      sha256 "965d5e976c53f2dd284248e626f47d69189c779f061e35aeb2016e419e4236cc"

      def install
        bin.install "otelinji"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hedhyw/otelinji/releases/download/v0.2.2/otelinji_darwin_arm64.tar.gz"
      sha256 "9f13c5ed46619649dd249bab491ee8e55d582e0a525f2684e043368643f35094"

      def install
        bin.install "otelinji"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/otelinji/releases/download/v0.2.2/otelinji_linux_amd64.tar.gz"
      sha256 "69f196d5039efa63dbea5434b372a04db613dd7885b332b5d95e80adb4ea0bd2"

      def install
        bin.install "otelinji"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/otelinji/releases/download/v0.2.2/otelinji_linux_arm.tar.gz"
      sha256 "71e39c5ee9d1ede9328cc8ae25a5f0a84fec8a0e1de3a82aab298de8b276eccf"

      def install
        bin.install "otelinji"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/otelinji/releases/download/v0.2.2/otelinji_linux_arm64.tar.gz"
      sha256 "65551b641d723d73521dfe2c00b0d21e7316fee16cfe949b4987ce2cf07e115d"

      def install
        bin.install "otelinji"
      end
    end
  end

  test do
    system "#{bin}/otelinji", "-help"
  end
end
